[33m28f17f9[m[33m ([m[1;36mHEAD[m[33m, [m[1;31morigin/main[m[33m)[m Finished pop up message
[33mbb1034b[m Added update and delete in Project section
[33m521f3a9[m Projects can now be added
[33mf177611[m Added skill and project models
[33m4823d12[m Added contact section and form
[33m0826ec8[m Added Portfolio section
[33m2edb71b[m Enhanced portfolio
[33med4b664[m Install Breeze
[33ma41fcd8[m Set up a fresh Laravel app
